# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2022-09-13T15:02:06+00:00

from fastapi import FastAPI

app = FastAPI(
    version="0.1.0",
    title="Social links service",
    description="",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
    openapi_url="/api/v1/communications/openapi.json",
)
