# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2022-09-13T12:41:44+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Communication(BaseModel):
    user_ids: List[int]


class SocialLink(BaseModel):
    user_ids: List[int]
    communication_count: int


class SendCommunicationResponse(BaseModel):
    communication_id: int


class Statistics(BaseModel):
    minimum_communication_count: int
    average_communication_count: float
    maximum_communication_count: int


class SocialGraph(BaseModel):
    social_links: List[SocialLink]
    statistics: Statistics
