# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2022-09-12T23:23:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class UserIDs(BaseModel):
    __root__: List[int] = Field(..., title='UserIDs')


class SocialLink(BaseModel):
    user_ids: UserIDs
    communication_count: int


class SendCommunicationResponse(BaseModel):
    communication_id: int


class Statistics(BaseModel):
    minimum_communication_count: int
    average_communication_count: int
    maximum_communication_count: int


class Communication(BaseModel):
    user_ids: UserIDs


class SocialGraph(BaseModel):
    social_links: List[SocialLink]
    statistics: Statistics
